version: "3.8"

services:
  postgres:
    image: postgres:13.0-alpine
    container_name: Database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=access
      - POSTGRES_DB=PostgresSQL
      
  web:
    restart: always
    build:
      context: ./app/
      dockerfile: Dockerfile.prod
    container_name: Django
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py check --deploy &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/app/api
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.prod
    depends_on:
      - postgres

  nextjs:
    restart: always
    command: npm run dev
    container_name: Nextjs
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/frontend
    depends_on:
      - web

volumes:
  postgres_data:
