version: "3.8"

services:
  postgres:
    image: postgres:13.0-alpine
    container_name: Database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=access
      - POSTGRES_DB=PostgresSQL
      
  web:
    restart: on-failure
    build: ./app
    container_name: Django
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/app/api
    ports:
      - 8080:80
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

  nextjs:
    restart: on-failure
    command: npm run dev
    container_name: Nextjs
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/frontend
    depends_on:
      - web
      
  nginx:
    build: ./nginx
    container_name: nginx
    hostname: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app/:/nginx/nginx.conf
      # - <path/to/your/certs>:/etc/ssl/private

volumes:
  postgres_data:
