version: '3.8'

services:
  backend:
    restart: always
    build: ./app
    container_name: Django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/app/api
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    container_name: Database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=backend_dev

  nextjs:
    restart: always
    command : npm run dev
    container_name: Nextjs
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: