import Footer from "./Footer"
import Navbar from "./Navbar"
import Head from 'next/head'


const Layout = ({ children }: any) => {
    return (
        <div>
            <Head>
                <title>Eilya</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />
            {children}
            <Footer />
        </div>
    )
}

export default Layout
