import Footer from "./Footer"
import Navbar from "./Navbar"
import Head from 'next/head'

interface Props {
    lastThreePosts: Array<object>,
    children: any
}

const Layout = ({ lastThreePosts, children }: Props) => {
    return (
        <div>
            <Head>
                <title>Eilya</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />
            {children}
            <Footer lastThreePosts={lastThreePosts}/>
        </div>
    )
}

export default Layout
